[FIX] brew clang17 install

diff --git a/setup-package-manager/install b/setup-package-manager/install
--- a/setup-package-manager/install
+++ b/setup-package-manager/install
@@ -8,21 +8,21 @@ install_via_brew()
     package_version=$(echo $brew_package_name | awk -F '@' '{print $2; }') # 15
 
     # General idea:
-    # `brew list --versions` returns 1 if package is installed, and 0 otherwise. By combining it with some other command
-    # via `&&`, we can run the second command depending on whether the package is installed.
+    # `brew list --versions` returns true (0) if package is installed, and false (1) otherwise.
     # package_name: The package name without a version, e.g. "ccache" and "gcc".
     # brew_package_name: The package followed by an optional version, e.g. "ccache" and "gcc@11".
     # `--force-bottle` will cause brew to use precompiled binaries. Sometimes brew likes to build compilers from scratch.
 
-    # If the package is installed, we unlink the package. brew unlink does not take a version.
-    brew list --versions $brew_package_name && \
-        brew unlink $package_name \
-    || true
-
     # If the package is installed, we upgrade. Otherwise, we install it.
-    brew list --versions $brew_package_name && \
-        brew upgrade --force-bottle $brew_package_name \
-    || brew install --force-bottle --overwrite $brew_package_name
+    if brew list --versions $brew_package_name; then
+        # Unlink the package. brew unlink does not take a version.
+        brew unlink $package_name || true
+        # Install dependencies separately and ignore errors. E. g., python3.11 (dependency of llvm@17) fails to link.
+        brew install --force-bottle --overwrite --only-dependencies $brew_package_name || true
+        brew install --force-bottle --overwrite $brew_package_name
+    else
+        brew upgrade --force-bottle $brew_package_name
+    fi
 
     # We link the package, i.e. we add symlinks into /usr/local/bin. They requested version of the package should superseed
     # other installed versions (`--overwrite`). For example, when requesting gcc@10 while gcc@11 is already installed and
@@ -44,9 +44,6 @@ if [ "$RUNNER_OS" == "Linux" ]; then
         sudo apt-get install --yes $(echo ${ARG/gcc/g++})
     done
 elif [ "$RUNNER_OS" == "macOS" ]; then
-    export HOMEBREW_NO_INSTALL_CLEANUP=1 # Do not run brew cleanup automatically.
-    export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 # Do not automatically update packages.
-
     for ARG in "$@"; do
         # clang-15 -> llvm@15, gcc-13 -> gcc@13
         if [[ $ARG == clang* || $ARG == gcc* ]]; then
