[MISC] Do not allow relative paths

diff --git a/documentation_deploy_preview/action.yml b/documentation_deploy_preview/action.yml
--- a/documentation_deploy_preview/action.yml
+++ b/documentation_deploy_preview/action.yml
@@ -41,6 +41,14 @@ runs:
       shell: bash
       run: echo "::error title=Error::This action can only be run on pull requests."; exit 1
 
+    - name: Input Check
+      shell: bash
+      run: |
+        if [[ "${{ inputs.deploy_base_path }}" != $(readlink -m "${{ inputs.deploy_base_path }}") ]]; then
+            echo "::error title=Error::deploy_base_path must be an absolute path and not end in '/'."
+            exit 1
+        fi
+
     - name: Package Preview Dual Documentation
       if: ${{ inputs.source_path_developer_doc != '' }}
       shell: bash
diff --git a/documentation_deploy_production/action.yml b/documentation_deploy_production/action.yml
--- a/documentation_deploy_production/action.yml
+++ b/documentation_deploy_production/action.yml
@@ -56,6 +56,14 @@ runs:
           echo "::error title=Error::deploy_path_developer_doc must be set if source_path_developer_doc is set."
           exit 1
         fi
+        if [[ "${{ inputs.deploy_path_user_doc }}" != $(readlink -m "${{ inputs.deploy_path_user_doc }}") ]]; then
+            echo "::error title=Error::deploy_path_user_doc must be an absolute path and not end in '/'."
+            exit 1
+        fi
+        if [[ "${{ inputs.deploy_path_developer_doc }}" != $(readlink -m "${{ inputs.deploy_path_developer_doc }}") ]]; then
+            echo "::error title=Error::deploy_path_developer_doc must be an absolute path and not end in '/'."
+            exit 1
+        fi
 
     - name: Deploy User documentation
       if: ${{ inputs.source_path_user_doc != '' }}
